[2024-10-27 22:54:34,960: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-28 01:15:35,426: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-28 01:15:35,433: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-28 01:15:35,444: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-28 01:15:35,451: INFO: common: Directory created at artifacts]
[2024-10-28 01:20:17,617: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-28 01:20:17,619: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-28 01:20:17,621: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-28 01:20:17,621: INFO: common: Directory created at artifacts]
[2024-10-28 01:20:31,889: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-28 01:20:31,890: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-28 01:20:31,891: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-28 01:20:31,892: INFO: common: Directory created at artifacts]
[2024-10-28 01:20:41,710: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-28 01:20:41,711: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-28 01:20:41,712: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-28 01:20:41,713: INFO: common: Directory created at artifacts]
[2024-10-28 01:20:41,714: INFO: common: Directory created at artifacts/data_ingestion]
[2024-10-28 01:23:22,867: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-28 01:23:22,868: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-28 01:23:22,869: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-28 01:23:22,869: INFO: common: Directory created at artifacts]
[2024-10-28 01:23:22,870: INFO: common: Directory created at artifacts/data_ingestion]
[2024-10-28 01:23:23,635: INFO: 393514883: artifacts/data_ingestion/data.zip downloaded with following info 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 2253:3D1C44:5BC63:72893:671E9A32
Accept-Ranges: bytes
Date: Sun, 27 Oct 2024 19:53:23 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100020-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1730058803.424782,VS0,VE286
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 55755d1b6fc786f8a0c456f13752ed5840a73e07
Expires: Sun, 27 Oct 2024 19:58:23 GMT
Source-Age: 0

]
[2024-10-28 01:49:35,597: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-28 01:49:35,598: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-28 01:49:35,598: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-28 01:49:35,599: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-28 01:49:35,599: INFO: common: Directory created at artifacts]
[2024-10-28 01:49:35,599: INFO: common: Directory created at artifacts/data_ingestion]
[2024-10-28 01:49:36,376: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded with following info 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 2253:3D1C44:5BC63:72893:671E9A32
Accept-Ranges: bytes
Date: Sun, 27 Oct 2024 20:19:36 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100024-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1730060376.145680,VS0,VE281
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 0e39e1d873d04e61ed3e10d1223bb1dbca169817
Expires: Sun, 27 Oct 2024 20:24:36 GMT
Source-Age: 0

]
[2024-10-28 01:49:36,379: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 08:20:32,622: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 08:20:32,626: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 08:20:32,632: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 08:20:32,633: INFO: common: Directory created at artifacts]
[2024-10-29 08:20:32,635: INFO: common: Directory created at artifacts/data_validation]
[2024-10-29 08:20:49,051: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 08:20:49,053: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 08:20:49,055: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 08:20:49,056: INFO: common: Directory created at artifacts]
[2024-10-29 08:20:49,057: INFO: common: Directory created at artifacts/data_validation]
[2024-10-29 08:20:49,057: INFO: common: Directory created at artifacts/data_validation]
[2024-10-29 08:34:06,411: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 08:34:06,412: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 08:34:06,412: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 08:34:06,413: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 08:34:06,414: INFO: common: Directory created at artifacts]
[2024-10-29 08:34:06,414: INFO: common: Directory created at artifacts/data_ingestion]
[2024-10-29 08:34:06,414: INFO: data_ingestion: artifacts/data_ingestion/data.zip file already exists]
[2024-10-29 08:34:06,415: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 08:34:06,415: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 08:34:06,416: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 08:34:06,416: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 08:34:06,417: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 08:34:06,417: INFO: common: Directory created at artifacts]
[2024-10-29 08:34:06,417: INFO: common: Directory created at artifacts/data_validation]
[2024-10-29 08:34:06,420: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 11:27:59,613: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 11:27:59,615: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 11:27:59,617: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 11:27:59,618: INFO: common: Directory created at artifacts]
[2024-10-29 11:27:59,619: INFO: common: Directory created at artifacts/data_transformation]
[2024-10-29 11:28:22,577: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 11:28:22,579: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 11:28:22,581: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 11:28:22,581: INFO: common: Directory created at artifacts]
[2024-10-29 11:28:22,582: INFO: common: Directory created at artifacts/data_transformation]
[2024-10-29 11:28:46,753: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 11:28:46,754: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 11:28:46,756: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 11:28:46,756: INFO: common: Directory created at artifacts]
[2024-10-29 11:28:46,757: INFO: common: Directory created at artifacts/data_transformation]
[2024-10-29 11:29:15,532: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 11:29:15,534: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 11:29:15,535: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 11:29:15,536: INFO: common: Directory created at artifacts]
[2024-10-29 11:29:15,537: INFO: common: Directory created at artifacts/data_transformation]
[2024-10-29 11:29:15,581: INFO: 2928414502: Test test split done]
[2024-10-29 11:29:15,582: INFO: 2928414502: (1199, 12)]
[2024-10-29 11:29:15,582: INFO: 2928414502: (400, 12)]
[2024-10-29 11:38:11,352: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 11:38:11,354: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 11:38:11,354: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 11:38:11,355: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 11:38:11,355: INFO: common: Directory created at artifacts]
[2024-10-29 11:38:11,355: INFO: common: Directory created at artifacts/data_ingestion]
[2024-10-29 11:38:11,355: INFO: data_ingestion: artifacts/data_ingestion/data.zip file already exists]
[2024-10-29 11:38:11,357: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 11:38:11,357: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 11:38:11,358: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 11:38:11,359: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 11:38:11,359: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 11:38:11,359: INFO: common: Directory created at artifacts]
[2024-10-29 11:38:11,359: INFO: common: Directory created at artifacts/data_validation]
[2024-10-29 11:38:11,362: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 11:38:11,362: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 11:38:11,363: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 11:38:11,363: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 11:38:11,364: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 11:38:11,365: INFO: common: Directory created at artifacts]
[2024-10-29 11:38:11,365: INFO: common: Directory created at artifacts/data_transformation]
[2024-10-29 11:38:11,374: INFO: data_transformation: Test test split done]
[2024-10-29 11:38:11,374: INFO: data_transformation: (1199, 12)]
[2024-10-29 11:38:11,374: INFO: data_transformation: (400, 12)]
[2024-10-29 11:38:11,374: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 20:00:22,536: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 20:00:22,537: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 20:00:22,537: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 20:00:22,538: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 20:00:22,538: INFO: common: Directory created at artifacts]
[2024-10-29 20:00:22,539: INFO: common: Directory created at artifacts/data_ingestion]
[2024-10-29 20:00:22,539: INFO: data_ingestion: artifacts/data_ingestion/data.zip file already exists]
[2024-10-29 20:00:22,541: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 20:00:22,541: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 20:00:22,542: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 20:00:22,542: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 20:00:22,543: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 20:00:22,544: INFO: common: Directory created at artifacts]
[2024-10-29 20:00:22,544: INFO: common: Directory created at artifacts/data_validation]
[2024-10-29 20:00:22,552: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 20:00:22,552: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 20:00:22,553: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 20:00:22,553: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 20:00:22,554: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 20:00:22,554: INFO: common: Directory created at artifacts]
[2024-10-29 20:00:22,554: INFO: common: Directory created at artifacts/data_transformation]
[2024-10-29 20:00:22,569: INFO: data_transformation: Test test split done]
[2024-10-29 20:00:22,569: INFO: data_transformation: (1199, 12)]
[2024-10-29 20:00:22,569: INFO: data_transformation: (400, 12)]
[2024-10-29 20:00:22,569: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 20:00:22,569: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 20:00:22,571: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 20:00:22,571: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 20:00:22,573: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 20:00:22,573: INFO: common: Directory created at artifacts]
[2024-10-29 20:00:22,573: INFO: common: Directory created at artifacts/model_trainer]
[2024-10-29 20:00:22,573: ERROR: main: "'ConfigBox' object has no attribute 'train_data_name'"]
Traceback (most recent call last):
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 593, in __getitem__
    return super().__getitem__(item)
KeyError: 'train_data_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 632, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 620, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'train_data_name'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 634, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'train_data_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/config_box.py", line 29, in __getattr__
    return super().__getattr__(item)
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 648, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'train_data_name'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 593, in __getitem__
    return super().__getitem__(item)
KeyError: 'train_data_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 632, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 620, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'train_data_name'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 634, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'train_data_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/main.py", line 41, in <module>
    obj.initiate_model_training()
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/src/datascience/pipeline/model_trainer_pipeline.py", line 12, in initiate_model_training
    model_trainer_config = config.get_model_trainer_config()
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/src/datascience/config/configuration.py", line 62, in get_model_trainer_config
    model_name = config.train_data_name,
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/config_box.py", line 31, in __getattr__
    return super().__getattr__(item.lower())
  File "/Users/mukulagarwal/Desktop/Projects/datascienceproject/prjt3/lib/python3.10/site-packages/box/box.py", line 648, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'train_data_name'"
[2024-10-29 20:01:28,038: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 20:01:28,040: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 20:01:28,040: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 20:01:28,041: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 20:01:28,041: INFO: common: Directory created at artifacts]
[2024-10-29 20:01:28,041: INFO: common: Directory created at artifacts/data_ingestion]
[2024-10-29 20:01:28,041: INFO: data_ingestion: artifacts/data_ingestion/data.zip file already exists]
[2024-10-29 20:01:28,043: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 20:01:28,043: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 20:01:28,044: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 20:01:28,044: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 20:01:28,045: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 20:01:28,045: INFO: common: Directory created at artifacts]
[2024-10-29 20:01:28,045: INFO: common: Directory created at artifacts/data_validation]
[2024-10-29 20:01:28,047: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 20:01:28,048: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 20:01:28,049: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 20:01:28,049: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 20:01:28,050: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 20:01:28,050: INFO: common: Directory created at artifacts]
[2024-10-29 20:01:28,050: INFO: common: Directory created at artifacts/data_transformation]
[2024-10-29 20:01:28,060: INFO: data_transformation: Test test split done]
[2024-10-29 20:01:28,060: INFO: data_transformation: (1199, 12)]
[2024-10-29 20:01:28,060: INFO: data_transformation: (400, 12)]
[2024-10-29 20:01:28,060: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
[2024-10-29 20:01:28,060: INFO: main: >>>>>>> stage {STAGE_NAME} started >>>>>>]
[2024-10-29 20:01:28,061: INFO: common: yaml file at config/config.yaml loaded successfully]
[2024-10-29 20:01:28,062: INFO: common: yaml file at params.yaml loaded successfully]
[2024-10-29 20:01:28,062: INFO: common: yaml file at schema.yaml loaded successfully]
[2024-10-29 20:01:28,062: INFO: common: Directory created at artifacts]
[2024-10-29 20:01:28,062: INFO: common: Directory created at artifacts/model_trainer]
[2024-10-29 20:01:28,074: INFO: main: >>>>>>> stage {STAGE_NAME} completed >>>>>>]
